POST http://localhost/indianbychoice/api/home.php HTTP/1.1
content-type: application/json

{
    "uid": "1"
}

# POST "https://securegw-stage.paytm.in/theia/api/v1/initiateTransaction?mid=xwUKNw33672785335079&orderId=OrderNo999999994152" HTTP/1.1
# content-type: application/json

# {
#     "head": {
#         "version": "v1",
#         "channelId": "WEB",
#         "requestTimestamp": "1625949523",
#         "signature": "ng2+3b/+4qLfer+VbGpvcM+PEywvvvz4usXvFQljv24k7jb0OoQu7H3O+vWlJMGQEcZPeaTKIQWRJf/H1xvG8gl/kp+jBa0EdNJ6gt376Cw="
#     },
#     "body": {
#         "requestType": "Payment",
#         "mid": "xwUKNw33672785335079",
#         "websiteName": "WEBSTAGING",
#         "orderId": "OrderNo999999994152",
#         "callbackUrl": "https://indianbychoice.com/",
#         "txnAmount": {
#             "value": "5000",
#             "currency": "INR"
#         },
#         "userInfo": {
#             "custId": "1",
#             "mobile": "9903348771",
#             "email": "developer.subho57@gmail.com",
#             "firstName": "Subhankar",
#             "lastName": "Pal"
#         }
#     }
# }